[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[fmt]
tab_width = 2
quote_style = "single"
multiline_func_header = "params_first"
single_line_statement_blocks = "preserve"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${ETH_MAINNET_RPC_URL}"
pulsechain = "${PULSECHAIN_RPC_URL}"
pulsechain-testnet = "${PULSECHAIN_TESTNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
